language: node_js

env:
  - TEST_APP_URI=http://localhost:3000/change  # Needs to be on /change see package.json homepage

script:
  - npm run lint
  - npm test -- --coverage
  - npx codecov@3.1.0
  - npm run build
  - ln -s ./build/ ./change
  - npx serve@10.1.1 -p 3000 &
  - sleep 5
  - CYPRESS_baseUrl=$TEST_APP_URI npm run test:e2e

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
